# 08 - RAG Benchmark Suite (Retrieval + Generation + End-to-End)

This notebook runs a structured benchmark on all SRS files using question sets under:
`data/benchmarks/rag_eval/questions/`.

Outputs are saved under:
`data/outputs/evaluation/rag_benchmark/`

In [1]:
from pathlib import Path
import subprocess
import sys
import pandas as pd

In [2]:
RAG_LAB = Path("..").resolve()
SCRIPT = RAG_LAB / "scripts" / "run_rag_benchmark.py"

cmd = [
    sys.executable,
    str(SCRIPT),
    "--max-questions-per-srs",
    "10",
    "--k",
    "5",
    "--threshold",
    "0.72",
    "--answer-temperature",
    "0.1",
]

proc = subprocess.run(cmd, cwd=RAG_LAB, text=True, capture_output=True)
print(proc.stdout)
if proc.returncode != 0:
    print(proc.stderr)
    raise RuntimeError(f"Benchmark failed with code {proc.returncode}")

Saved benchmark outputs to: D:\Qbrainpython\QBrain\rag_lab\data\outputs\evaluation\rag_benchmark

Overall summary:
                        metric     value
                    srs_files  5.000000
                    questions 45.000000
              retrieval_hit@5  1.000000
        retrieval_precision@5  0.200000
           retrieval_recall@5  1.000000
                retrieval_mrr  1.000000
generation_accuracy_sim>=0.72  0.733333
    generation_avg_similarity  0.789846
             e2e_success_rate  0.733333

In [3]:
OUT = RAG_LAB / "data" / "outputs" / "evaluation" / "rag_benchmark"

overall = pd.read_csv(OUT / "overall_summary.csv")
retrieval = pd.read_csv(OUT / "retrieval" / "retrieval_summary_by_srs.csv")
generation = pd.read_csv(OUT / "generation" / "generation_summary_by_srs.csv")
e2e = pd.read_csv(OUT / "e2e" / "e2e_summary_by_srs.csv")
failures = pd.read_csv(OUT / "diagnostics" / "failure_breakdown.csv")
by_category = pd.read_csv(OUT / "diagnostics" / "metrics_by_category.csv")

print("Overall")
display(overall)
print("Retrieval by SRS")
display(retrieval)
print("Generation by SRS")
display(generation)
print("End-to-end by SRS")
display(e2e)
print("Failure breakdown")
display(failures)
print("Metrics by category")
display(by_category)

Overall

                          metric      value
0                      srs_files   5.000000
1                      questions  45.000000
2                retrieval_hit@5   1.000000
3          retrieval_precision@5   0.200000
4             retrieval_recall@5   1.000000
5                  retrieval_mrr   1.000000
6  generation_accuracy_sim>=0.72   0.733333
7      generation_avg_similarity   0.789846
8               e2e_success_rate   0.733333

Retrieval by SRS

,srs_file,questions,hit_rate,precision_at_k,recall_at_k,mrr
0,2007 - ertms.pdf,10,1.0,0.2,1.0,1.0
1,2008 - keepass.pdf,10,1.0,0.2,1.0,1.0
2,2009 - inventory 2.0.pdf,10,1.0,0.2,1.0,1.0
3,2010 - gparted.pdf,5,1.0,0.2,1.0,1.0
4,JDECo_SRS.docx[1].pdf,10,1.0,0.2,1.0,1.0

Generation by SRS

,srs_file,questions,answer_accuracy,avg_similarity,min_similarity,max_similarity
0,2007 - ertms.pdf,10,0.9,0.854060,0.703743,0.930067
1,2008 - keepass.pdf,10,0.8,0.749534,0.560532,0.855776
2,2009 - inventory 2.0.pdf,10,0.6,0.765480,0.648260,0.941584
3,2010 - gparted.pdf,5,0.6,0.807569,0.633013,0.926387
4,JDECo_SRS.docx[1].pdf,10,0.7,0.781449,0.587598,0.955405

End-to-end by SRS

,srs_file,questions,e2e_success_rate,retrieval_hit_rate,generation_accuracy
0,2007 - ertms.pdf,10,0.9,1.0,0.9
1,2008 - keepass.pdf,10,0.8,1.0,0.8
2,2009 - inventory 2.0.pdf,10,0.6,1.0,0.6
3,2010 - gparted.pdf,5,0.6,1.0,0.6
4,JDECo_SRS.docx[1].pdf,10,0.7,1.0,0.7

Failure breakdown

      failure_type  count
0             pass     33
1  generation_fail     12

Metrics by category

,category,questions,e2e_success_rate,retrieval_hit_rate,generation_accuracy,avg_similarity
0,direct,45,0.733333,1.0,0.733333,0.789846